apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: workshop-backup-azure-object-store
spec:
  retentionPolicy: "1d"
  configuration:
    azureCredentials:
      storageAccount:
        name: azure-storage-account-credentials
        key: account_name
      storageKey:
        name: azure-storage-account-credentials
        key: account_key
    # Please change the destinationPath to your own Azure Blob Storage URL
    destinationPath: https://cnpgworkshop.blob.core.windows.net/aa773-workshop-pg-backup/v1
    wal:
      compression: gzip
  instanceSidecarConfiguration:
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1000Mi
