apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: workshop-backup-azure-object-store
spec:
  retentionPolicy: "3d"
  configuration:
    # Please change the destinationPath to your own Azure Blob Storage URL
    destinationPath: https://workshop.blob.core.windows.net/aaXXX-workshop-pg-backup/v1
    wal:
      compression: gzip
  instanceSidecarConfiguration:
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1000Mi
