# CNPG can generate db credentials for you
# but for demo purposes we will create a secret with the credentials and reference it in the cluster spec.
# in production you should consider using a secret management solution like HashiCorp Vault or AWS Secrets Manager to manage your database credentials more securely.
apiVersion: v1
kind: Secret
metadata:
  name: app-user
type: Opaque
stringData:
  username: app
  password: SuperSecurePassword123!