apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: replace-restore-azure-object-store
spec:
  configuration:
    destinationPath: https://replace.blob.core.windows.net/barman-pg-backup/v1
    wal:
      maxParallel: 8
  instanceSidecarConfiguration:
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1000Mi
