apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: workshop-pg-pooler-rw
spec:
  cluster:
    name: workshop-pg-cluster
  instances: 3
  type: rw
  template:
    metadata:
      labels:
        app: pooler
        intility-logging: default
    spec:
      containers:
        - name: pgbouncer
          resources:
            requests:
              cpu: 80m
              memory: 24Mi
            limits:
              memory: 128Mi
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - pooler
              topologyKey: "kubernetes.io/hostname"
  pgbouncer:
    poolMode: session
    # When set to `true`, PgBouncer will disconnect from the PostgreSQL server, first waiting for all queries to complete, and pause all new client connections until this value is set to `false` (default).
    # https://cloudnative-pg.io/documentation/1.23/connection_pooling/#pausing-connections
    paused: false
    # PostgreSQL Host Based Authentication rules (lines to be appended to the pg_hba.conf file)
    # pg_hba:
    #   - ""

    # PgBouncer configuration options
    # Not all options are supported, see the documentation for the full list.
    # https://cloudnative-pg.io/documentation/1.23/connection_pooling/#pgbouncer-configuration-options
    # https://www.pgbouncer.org/config.html
    parameters:
      # Maximum number of client connections allowed.
      # Default value is 100.
      max_client_conn: "100"
      # How many server connections to allow per user/database pair.
      # Default value is 20.
      default_pool_size: "20"
